<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>mortgageApprovalLogic</name>
  <uuid>23b3ce54-94ea-4b0d-894f-ddecf9297f98</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	mortgageAmount is less than yearlyIncome
then
	set decision to true;
else
	set decision to false;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
